services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud:29-fpm
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./docker/volumes/nextcloud:/var/www/html
      - ./docker/nextcloud/hooks/:/docker-entrypoint-hooks.d/:ro
      - ./docker/nextcloud/files/:/files/:ro
      - ./docker/nextcloud/php/php.ini:/usr/local/etc/php/conf.d/zzz-secufile.ini:ro
      - ./:/app:ro
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
  
  web:
    image: nginx:1-alpine
    ports:
      - 80:80
      - 443:443
    links:
      - app
    depends_on:
      - app
    volumes:
      - ./:/app:ro
      - ./docker/volumes/nextcloud:/var/www/html:ro
      - ./docker/volumes/nginx:/etc/ssl/nginx/localhost:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  nextcloud:
  db: